import { StyleSheet } from 'react-native';
import { colors } from '../../styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: colors.surface,
    padding: 32,
    alignItems: 'center',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: colors.shadowDark,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  logo: {
    width: 100,
    height: 100,
    borderRadius: 24,
    marginBottom: 20,
    backgroundColor: colors.borderLight,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  companyName: {
    fontSize: 26,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warning + '15',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.warning + '30',
  },
  rating: {
    fontSize: 18,
    color: colors.warning,
    fontWeight: '800',
  },
  feedbackCount: {
    fontSize: 15,
    color: colors.textSecondary,
    marginLeft: 8,
    fontWeight: '600',
  },
  section: {
    backgroundColor: colors.surface,
    marginTop: 16,
    marginHorizontal: 20,
    padding: 24,
    borderRadius: 20,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
  },
  workType: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  address: {
    fontSize: 17,
    color: colors.textSecondary,
    lineHeight: 26,
    fontWeight: '500',
  },
  dateTimeContainer: {
    gap: 14,
  },
  dateTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.background,
    borderRadius: 12,
  },
  label: {
    fontSize: 16,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  value: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.2,
  },
  infoContainer: {
    gap: 14,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.background,
    borderRadius: 12,
  },
  workersValue: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.primary,
    letterSpacing: -0.3,
  },
  workersFullyBooked: {
    color: colors.error,
  },
  fullyBookedText: {
    fontSize: 15,
    color: colors.error,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.error + '10',
    borderRadius: 10,
  },
  priceSection: {
    alignItems: 'center',
    marginBottom: 32,
    paddingVertical: 32,
  },
  priceValue: {
    fontSize: 48,
    fontWeight: '900',
    color: colors.success,
    letterSpacing: -1,
  },
  errorText: {
    fontSize: 18,
    color: colors.textTertiary,
    textAlign: 'center',
    marginTop: 120,
    fontWeight: '600',
  },
});
